config/routes.rb
Rails.application.routes.draw do

  resources :runners, :races

  root to: 'runners#index'

end

app/models/race.rb
class Race < ActiveRecord::Base

	
end

app/models/runner.rb
class Runner < ActiveRecord::Base

  validates :firstname, presence: true
  validates :lastname, presence: true
  validates :address1, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zip, presence: true
  validates :gender, presence: true
  validates :age, presence: true,
                  numericality: { only_integer: true }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/races_controller.rb
class RacesController < ApplicationController

  def index
    @race = Race.new
  end

end

app/controllers/runners_controller.rb
class RunnersController < ApplicationController

  before_action :make_runner, only: [:index, :new, :show]
  layout "runner"

  def index
    @title = "- Home"
  end

  def new
    @title = "- Add a Runner"
    @runners = Runner.all
  end

  def create
    @runner = Runner.new(runner_params)
    if @runner.save
      redirect_to new_runner_path
    end
  end

  def show
    @runner = Runner.find(params[:id])
    @title = "- " + @runner['firstname'] + ' ' + @runner['lastname']
  end

  def destroy
    @runner = Runner.find(params[:id])
    @runner.destroy
    redirect_to new_runner_path
  end

  def make_runner
    @runner = Runner.new
  end

  private

  def runner_params
      params.require(:runner).permit(:firstname, :lastname, :address1, :address2, :city, :state, :zip, :phone, :school, :gender, :age)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/races_helper.rb
module RacesHelper
end

app/helpers/runner_helper.rb
module RunnerHelper

  def runner_name(first, last)
    first + " " + last
  end

  def us_states
    [
      ['Alabama', 'AL'],
      ['Alaska', 'AK'],
      ['Arizona', 'AZ'],
      ['Arkansas', 'AR'],
      ['California', 'CA'],
      ['Colorado', 'CO'],
      ['Connecticut', 'CT'],
      ['Delaware', 'DE'],
      ['District of Columbia', 'DC'],
      ['Florida', 'FL'],
      ['Georgia', 'GA'],
      ['Hawaii', 'HI'],
      ['Idaho', 'ID'],
      ['Illinois', 'IL'],
      ['Indiana', 'IN'],
      ['Iowa', 'IA'],
      ['Kansas', 'KS'],
      ['Kentucky', 'KY'],
      ['Louisiana', 'LA'],
      ['Maine', 'ME'],
      ['Maryland', 'MD'],
      ['Massachusetts', 'MA'],
      ['Michigan', 'MI'],
      ['Minnesota', 'MN'],
      ['Mississippi', 'MS'],
      ['Missouri', 'MO'],
      ['Montana', 'MT'],
      ['Nebraska', 'NE'],
      ['Nevada', 'NV'],
      ['New Hampshire', 'NH'],
      ['New Jersey', 'NJ'],
      ['New Mexico', 'NM'],
      ['New York', 'NY'],
      ['North Carolina', 'NC'],
      ['North Dakota', 'ND'],
      ['Ohio', 'OH'],
      ['Oklahoma', 'OK'],
      ['Oregon', 'OR'],
      ['Pennsylvania', 'PA'],
      ['Puerto Rico', 'PR'],
      ['Rhode Island', 'RI'],
      ['South Carolina', 'SC'],
      ['South Dakota', 'SD'],
      ['Tennessee', 'TN'],
      ['Texas', 'TX'],
      ['Utah', 'UT'],
      ['Vermont', 'VT'],
      ['Virginia', 'VA'],
      ['Washington', 'WA'],
      ['West Virginia', 'WV'],
      ['Wisconsin', 'WI'],
      ['Wyoming', 'WY']
    ]
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Race Management <%= @title %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="page-wrap">

    <%= yield %>

  </div>
</body>
</html>

app/views/layouts/runner.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Race Management <%= @title %></title>
  <%= stylesheet_link_tag    'runners', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://developers.google.com/maps/documentation/javascript/sexamples/default.css" />
  <script src="https://maps.googleapis.com/maps/api/js?v=3&sensor=false"></script>

  <%= javascript_include_tag 'runners', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="page-wrap">

    <%= yield %>

  </div>
</body>
</html>

app/views/races/index.html.erb
<h1>Races Page</h1>

<hr />

<h3>Dashboard</h3>
<%= link_to "Create a Race", new_race_path %>

app/views/races/new.html.erb
<h1>Create a Race</h1>

app/views/runners/_runner_block.html.erb
<h3><%= runner_name(runner.firstname, runner.lastname) %></h3>
<hr />
<div class="runnerBlock">
  <div class="runnerData">
    <%= runner.address1 %></br>
    <%- if !runner.address2.blank? %>
      <%= runner.address2 %></br>
    <%- end %></br>
    <%= runner.city %> <%= runner.state %> <%= runner.zip %></br>
    <%- if !runner.phone.blank? %>
      <%= runner.phone %></br>
    <%- end %>

    <%- if !runner.school.blank? %>
      <%= runner.school %></br>
    <%- end %>

    <%- if !runner.gender.blank? %>
      Gender: <%= runner.gender %><br />
    <%- end %>

    <%- if !runner.gender.blank? %>
      Age: <%= runner.age %>
    <%- end %>
  </div>
  <div id="map_canvas" class="map_canvas"></div>
  <!--<script>loadMap('<%= runner.address1 %>', '<%= runner.city %>', '<%= runner.state %>')</script>-->
  <script>
    google.maps.visualRefesh = true;
    var map;

    function initialize()
    {
      var address = '<%= runner.address1 %>';
      var city =  '<%= runner.city %>';
      var state = '<%= runner.state %>';
      var addrTitle = address + " " + city + ", " + state;
      var addr = address.split(' ').join('+') + ",+" + city.split(' ').join('+') + ",+" + state;
      var myLatLng;
      getMapLatLong(addr, function(coords){
        myLatLng = new google.maps.LatLng(coords[0],coords[1]);
        var mapOptions = {
          zoom: 14,
          center: myLatLng,
          mapTypeId: google.maps.MapTypeId.HYBRID
        };
        map = new google.maps.Map(document.getElementById('map_canvas'), mapOptions);

        var marker = new google.maps.Marker({
          position: myLatLng,
          map: map,
          title: addrTitle
        })
      })
    }

    function getMapLatLong(address, callback){
      var addLat;
      var addLong;

      var mapAPI = "http://maps.google.com/maps/api/geocode/json?address=" + address + "&sensor=false"
      $.getJSON(mapAPI, function(data){

        addLat = data.results[0].geometry.location.lat;
        addLong = data.results[0].geometry.location.lng;
        coordinates = [addLat, addLong];

        if(addLat != null && addLong != null)
        {
          callback(coordinates);
        }
        else
        {
          $("#map_canvas").css("display", "none");
        }

      });
    }

    google.maps.event.addDomListener(window,'load', initialize);
  </script>
  <div id="delete">
    <%= link_to "Back", :back %> |
    <%= link_to "Delete Runner", runner_path(runner), method: :delete, data: {confirm: "Are you sure?"} %>
  </div>
</div>

app/views/runners/index.html.erb
<h1>Runners App</h1>

<hr />

<h3>Dashboard</h3>
<%= link_to "Create a Runner", new_runner_path %> | <%= link_to "Races Dashboard", races_path %>

app/views/runners/new.html.haml
%h1 Running Camp Registration
.formContainer
  %h4 Runners Form
  %hr/
  %p We appologize for the long form, but it allows us to collect everything we need for your registration. This way, the only thing you will be emailed before camp will be the instructions and directions to get to camp and what to bring! Thank you.
  %p.italic.note * Indicates Required Filed
  = form_for @runner do |f|
    First name: #{f.text_field :firstname, placeholder: '*required'}
    %br/
    Last name: #{f.text_field :lastname, placeholder: '*required'}
    %br/
    Address 1: #{f.text_field :address1, placeholder: '*required'}
    %br/
    Address 2: #{f.text_field :address2}
    %br/
    City: #{f.text_field :city, placeholder: '*required'}
    %br/
    State: #{f.select :state, us_states, placeholder: '*required'}
    %br/
    ZIP: #{f.text_field :zip, placeholder: '*required'}
    %br/
    Phone: #{f.telephone_field :phone}
    %br/
    School Name: #{f.text_field :school}
    %br/
    Gender: #{f.text_field :gender, placeholder: '*required'}
    %br/
    Age: #{f.text_field :age, placeholder: '*required'}
    %br/
    = f.submit
- if !@runners.blank?
  #runnerList
    %h4 Current Runners
    %hr/
    - @runners.each_with_index do |r, index|
      .runnerBlock
        %strong= link_to runner_name(r.firstname, r.lastname), runner_path(id: r.id)
        %hr/
        = r.address1
        %br/
        - if !r.address2.blank?
          = r.address2
          %br/
        = r.city
        = r.state
        = r.zip
        %br/
        - if !r.phone.blank?
          = r.phone
          %br/
        = r.school
        %br/
        Gender: #{r.gender}
        %br/
        Age: #{r.age}
      - if index+1 != @runners.size
        %hr/

app/views/runners/oldnew.html.erb
  <h1>Myers Running Camp Registration</h1>

  <div class="formContainer">
    <h4>Runners Form</h4>
    <hr />
    <p>We appologize for the long form, but it allows us to collect everything we need for your registration. This way, the only thing you will be emailed before camp will be the instructions and directions to get to camp and what to bring! Thank you.</p>

    <p class="italic note">* Indicates Required Filed</p>


    <%= form_for @runner do |f| -%>

      First name: <%= f.text_field :firstname %><br />
      Last name: <%= f.text_field :lastname %><br />
      Address 1: <%= f.text_field :address1 %><br />
      Address 2: <%= f.text_field :address2 %><br />
      City: <%= f.text_field :city %><br />
      State: <%= f.text_field :state %><br />
      ZIP: <%= f.text_field :zip %><br />
      Phone: <%= f.telephone_field :phone %><br />
      School Name: <%= f.text_field :schoolname %><br />
      Gender: <%= f.text_field :gender %><br />
      Age: <%= f.text_field :age %><br />
      <%= f.submit %>

    <% end -%>
  </div>
  <%- if !@runners.blank? %>
    <div id="runnerList">
      <h4>Current Runners</h4>
      <hr />
        <%- @runners.each_with_index do |r, index| %>
          <div class="runnerBlock">
            <strong><%= link_to runner_name(r.firstname, r.lastname), runner_path(id: r.id) -%></strong>
            <hr />
            <%= r.address1 %></br>
            <%- if !r.address2.blank? %>
              <%= r.address2 %></br>
            <%- end %>
            <%= r.city %> <%= r.state %> <%= r.zip %></br>
            <%- if !r.phone.blank? %>
              <%= r.phone %></br>
            <%- end %>
            <%= r.schoolname %></br>
            Gender: <%= r.gender %><br />
            Age: <%= r.age %>
          </div>
          <%- if index+1 != @runners.size %>
            <hr />
          <%- end %>
        <%- end %>
    </div>
  <%- end %>

app/views/runners/show.html.erb
<%= render partial: "runner_block", locals: {runner: @runner} %>